#define CONFIG_SSID "Doinky"

#define CONFIG_PWD "QuinLikesMan"

/* TO GET WEBHOOK, DO !chores init AND COPY WEBHOOK LINK THROUGH INTEGRATION. INCLUDE EVERYTHING AFTER discord.com */
#define CONFIG_WEBHOOK "/api/webhooks/797737040103735326/X8HeZIgmS9Yq7ByW_WD6j5fDjftG-6UjOQ6gAgocb63XCdhNR8SfdM5cn4I4Y1x5YDWU"

#define CONFIG_TTS "false"
